kinematics_simulation:
  ros__parameters:
    dt: 0.0025
    sys.robo_rdi: 0.10
    sys.robo_dst: 0.50
    sys.n_rbt: 4
    sys.r_BtoR: [1.02, -0.30, 1.02, 0.20, 0.20, -0.515, -0.60, -0.515]
    init.xB: 0.0
    init.yB: 0.0
    init.thB: 0.0
    init.thR: [0.0, 0.0, 0.0, 0.0]
    frame.cart_parent: "world"
    frame.robot_parent: "odom"
    frame.cart: "base_link"
    frame.robot_prefix: "robot"
    frame.robot_suffix: "_base_2"
    sim.M_to_B_body_x: 1.0