export ACADOS_SOURCE_DIR=$HOME/acados
export ACADOS_INSTALL_DIR=$HOME/acados
export LD_LIBRARY_PATH=$ACADOS_INSTALL_DIR/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$ACADOS_INSTALL_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
export PYTHONPATH=$ACADOS_SOURCE_DIR/interfaces/acados_template:$PYTHONPATH