casadi_mpc_controller_node:
  ros__parameters:
    control_rate_hz: 10.0
    con.t_delta: 0.1
    con.n_hor: 20
    con.arg_bnd: 1000.0
    con.Q_err_trn_x: 100.0
    con.Q_err_trn_y: 100.0
    con.Q_err_ang: 1000.0 # 1000.0
    con.Q_hdg: 2000.0 # 2000.0
    con.Q_con: 2.5e-7
    con.Q_chg: 2.5e-2
    con.obstacle_buffer: -100.0
    sys.n_rbt: 2
    sys.cart_hgt: 1.03
    sys.cart_wdt: 2.04
    sys.robo_sze: 0.30
    sys.robo_dst: 0.50
    sys.robo_rdi: 0.10

    sys.u_lower: -20.0
    sys.u_upper: 20.0
    frame.map: "world"
    frame.cart: "object"
    frame.cart_parent: "world"
    frame.robot_parent: "world"
    frame.robot_prefix: "robot_"
    frame.robot_suffix: ""

    # # SDF (PNG-based signed distance map) - OpenCV disabled
    # sdf.png_path: "/home/jaewoo/ros2_workspace/multirobot_ws/src/mpc_controller_cpp/src/siheung_sdm.png"
    # sdf.resolution: 20.0   # pixels per meter
    # sdf.origin_x: -1.3
    # sdf.origin_y: 3.0
    #
